### ISSUE TITLE
Migrer le backend de Heroku vers Scalingo

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#149]
## Objectif

Ne plus être limité par le free tier d'Heroku (sleep du serveur, 10,000 lignes dans la DB)

## Détails

Scalingo est le "Heroku français". Le serveur deviendra payant (quelques € par mois), mais la base de donnée sera illimitée (quoique sans backup dans la version gratuite).

## Todo

- [x] Créer une application dans Scalingo
- [x] Faire un dump de la base de donnée d'Heroku, et l'importer dans Scalingo
- [x] Mettre à jour les variables d'environment dans le code : `VUE_APP_API_ENDPOINT` et le [Procfile](https://doc.scalingo.com/platform/app/procfile))
- [x] Pusher ces mises à jour pour faire le switch
- [x] Connecter le Metabase à la nouvelle base de donnée
