### ISSUE TITLE
Quiz : proposer des quizs similaires ou suivants à la fin

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#181]
## Objectif

Aider à la navigation de l'utilisateur

## Détails

On peut imaginer plusieurs scénarios : 
- proposer à l'utilisateur un quiz qu'il n'a pas encore fait (mais il faudrait garder la session)
- proposer les quizs les plus connus (sauf celui qu'il vient de finir)
- proposer le quiz suivant (dans le cas de quizs divisés en plusieurs parties)

Comment faire ?
- ManyToMany self relation avec les quizs
  - en M2M simple, la liste des quizs s'afficheront lors de l'export
  - mais si on rajoute un modèle through (par exemple pour avoir des champs supplémentaires), l'info ne sera pas dispo dans l'export. On devra exporter séparément. Mais c'est pas si mal en fait ?
    - champs supplémentaires ? type de relation : `suivant`, `similaire`

https://charlesleifer.com/blog/self-referencing-many-many-through/

## Questions en suspens

- Est-ce qu'on peut avoir plusieurs liens entre 2 quizs ?

## Todo

- [x] Pouvoir faire des liens entre les quizs grâce à un modèle `QuizRelationship` (M2M through) dans l'admin
- [x] Afficher les quizs suivants (et précédents) dans l'interface
- [x] Afficher les quizs jumeaux dans l'interface
- [x] Afficher les quizs similaires dans l'interface

**Comment by raphodn** [comment]
@Sarma38 je pensais définir les relations suivantes : 
- "suivant" (voir "précédent", je peux peut-être m'en passer)
- "jumeau"
- "similaire"

Tu en vois d'autres ?

exemples : 
Quiz 1 >>> "similaire" >>> Quiz 2
Quiz 10 Partie 1 >>> "suivant" >>> Quiz 11 Partie 2 >>> "suivant" >>> Quiz 12 Partie 3
Quiz 20 >>> "jumeau" >>> Quiz 21

**Comment by Sarma38** [comment]
Oui, c’est bien. En attendant de définir des parcours.
Autre point simple : varier les messages ‘bravo’ ‘dommage’ pour commenter la réponse. Kahoot en propose plein, ça donnerait un peu de fun, non ?

 

De : Raphael Odini <notifications@github.com> 
Envoyé : mardi 15 décembre 2020 13:38
À : raphodn/know-your-planet <know-your-planet@noreply.github.com>
Cc : Sarma38 <matthieumassart@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [raphodn/know-your-planet] Quiz : proposer des quizs similaires ou suivants à la fin (#181)

 

@Sarma38 <https://github.com/Sarma38>  je pensais définir les relations suivantes :

*	"suivant" (voir "précédent", je peux peut-être m'en passer)
*	"jumeau"
*	"similaire"

Tu en vois d'autres ?

exemples :
Quiz 1 >>> "similaire" >>> Quiz 2
Quiz 10 Partie 1 >>> "suivant" >>> Quiz 11 Partie 2 >>> "suivant" >>> Quiz 12 Partie 3
Quiz 20 >>> "jumeau" >>> Quiz 21

**Comment by raphodn** [comment]
Tu peux proposer des valeurs supplémentaires, voire même modifier cette liste ici : https://github.com/raphodn/know-your-planet/blob/927c339f60a323ac2b49595327539fc423672d2f/frontend/src/constants.js#L5

**Comment by Sarma38** [comment]
Pas réussi à modifier la ligne de code, alors je le mets ici :

 

'C\'est exact', 'En effet', 'Bien vu', 'Félicitations', 'Bravo', ‘Très fort’, ‘C’est bien ça. Coup de chance ?’, ‘Impressionnant’, ‘Ca c’est du génie’, ‘On applaudit’, ‘Rangez vos antisèches, c’est trop facile’
‘On ne baisse pas les bras’, ‘Rien n’est perdu’, ‘On croit en toi’, ‘Pas tombé loin’, ‘Essaie encore’, ‘Surtout, ne pas se décourager’, ‘La prochaine sera la bonne’, ‘ah…pas du tout’, ‘C’est raté’, ‘Vous vous êtes bien échauffé ?’

A étoffer !

 

Matthieu

 

De : Raphael Odini <notifications@github.com> 
Envoyé : mardi 15 décembre 2020 14:16
À : raphodn/know-your-planet <know-your-planet@noreply.github.com>
Cc : Sarma38 <matthieumassart@free.fr>; Mention <mention@noreply.github.com>
Objet : Re: [raphodn/know-your-planet] Quiz : proposer des quizs similaires ou suivants à la fin (#181)

 

Tu peux proposer des valeurs supplémentaires, voire même modifier cette liste ici : https://github.com/raphodn/know-your-planet/blob/927c339f60a323ac2b49595327539fc423672d2f/frontend/src/constants.js#L5

**Comment by raphodn** [comment]
Affichage des quizs jumeaux/similaires dans l'interface (+ amélioration de l'admin)
https://github.com/raphodn/know-your-planet/commit/8d7da91cc294dcbbc42350df2553ba4370af874a#diff-76309e68319bb8be4ef80e6e796168534de39f8d28cc3b934625d9ae1ddcca11
