### ISSUE TITLE
Ajouter un nouveau format de questions: Vrai/Faux

### ISSUE THREAD

**Issue by raphodn** [raphodn/know-your-planet#19]
## Objectif

Gérer le cas des questions Vrai / Faux

## Détails

Changements surtout dans le UI pour gérer le type QCM et V/F conjointement

## Todo

- [x] Rendre les champs answer_option_c et answer_option_d optionnels
- [x] Modifier un peu l'UI pour changer la tournure de la réponse en cas de réponse correcte ou erronée ?
- [x] Ajouter des questions V/F :)
